package org.example.analytics;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.analytics.model.Employee;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

public class DataParser {

    private static final Logger log = LoggerFactory.getLogger(DataParser.class);
    private static final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Parses a JSON file generated by program 1 into a list of Employee records.
     *
     * @param filePath path to the input JSON file
     * @return list of employees parsed from the file
     * @throws IOException if the file cannot be read or parsed
     */
    public List<Employee> parse(Path filePath) throws IOException {
        log.info("Parsing file: {}", filePath.getFileName());
        List<Employee> employees = objectMapper.readValue(
                filePath.toFile(),
                new TypeReference<List<Employee>>() {}
        );
        log.info("Parsed {} records from {}", employees.size(), filePath.getFileName());
        return employees;
    }
}
